feat: created bookings query endpoint
UW-SE-26/booking-backend pull request #30
Opened 2021-09-06 23:51 UTC by KevDev0247

#### **What does this PR do?**

Created bookings query endpoint
- added bookings query controller
- add query route

#### **How is this PR tested?**

Tested with postman (no auth requirement for queries)

#### **Checklist**

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] My merge commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)

2021-09-07 01:16 UTC, sunny-zuo requested changes

2021-09-07 01:16 UTC, sunny-zuo commented on src/routes/api/bookings/queryBookings.ts
> +    const bookerEmail = req.query.id;
This lets people arbitrarily view people's bookings - can we authenticate this request?

2021-09-07 01:16 UTC, sunny-zuo commented on src/routes/api/bookings/queryBookings.ts
> +                res.status(404).json({ error });
`404` on an arbitrary error doesn't make sense, and the return statement on the next line will only exit the promise.

2021-09-07 01:16 UTC, sunny-zuo commented on src/routes/api/bookings/queryBookings.ts
> +        // If no booker's discord id is included in the query, retrieve all the bookings and return the booking
Why do we need this endpoint?

2021-09-08 03:44 UTC, Notoh commented
Superseded by #32

2021-09-08 03:44 UTC, closed without merging